import RestraurantNav from "../components/RestraurantNav";

import MenuDesc from "../components/MenuDesc";
import { Metadata } from "next";
import { PrismaClient } from "@prisma/client";

export const metadata: Metadata = {
  title: "OpenTable | Menu",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchRestroMenu = async (slug: string) => {
  const restraurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  });

  if (!restraurant) {
    throw new Error("restaurant not found");
  }
  return restraurant.items;
};

async function Menu({ params }: { params: { slug: string } }) {
  const menu = await fetchRestroMenu(params.slug);
  console.log({ menu });

  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestraurantNav slug={params.slug} />
        <MenuDesc menu={menu} />
      </div>
    </>
  );
}

export default Menu;
