"use client";
import { ReduxProvider } from "@/redux/provider";
import Navbar from "./components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import "react-datepicker/dist/react-datepicker.css";
export const metadata: Metadata = {
  title: "OpenTable",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gray-100 min-h-screen w-screen px-40">
          <main className="max-w-screen-2xl m-auto bg-white">
            <ReduxProvider>
              <Navbar />
              {children}
            </ReduxProvider>
          </main>
        </main>
      </body>
    </html>
  );
}
